import { SuperTokensProvider } from './components/supertokensProvider'; // ★今作ったパーツを読み込む

export const metadata = {
  title: 'Minesweeper App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        {/* ★大元を先ほどの専用パーツで包む */}
        <SuperTokensProvider>{children}</SuperTokensProvider>
      </body>
    </html>
  );
}
